default_config:

homeassistant:
  packages: !include_dir_named packages/
  
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 0.0.0.0/0
      allow_bypass_login: true

tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

lovelace: !include lovelace.yaml

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - http://localhost:4000/vehicle-cards.js
